local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("background","ElvUI Blank", [[Interface\BUTTONS\WHITE8X8]])
LSM:Register("border", "ElvUI GlowBorder", [[Interface\AddOns\ElvUI\media\textures\glowTex.tga]])
LSM:Register("font", "ElvUI Alt-Font", [[Interface\AddOns\ElvUI\media\fonts\Continuum_Medium.ttf]])
LSM:Register("font","ElvUI Alt-Combat", [[Interface\AddOns\ElvUI\media\fonts\DieDieDie.ttf]])
LSM:Register("font","ElvUI Combat", [[Interface\AddOns\ElvUI\media\fonts\Action_Man.ttf]])
LSM:Register("font","ElvUI Font", [[Interface\AddOns\ElvUI\media\fonts\PT_Sans_Narrow.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("font", "ElvUI Pixel", [[Interface\AddOns\ElvUI\media\fonts\Homespun.ttf]],LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register("sound", "Awww Crap", [[Interface\AddOns\ElvUI\media\sounds\awwcrap.mp3]])
LSM:Register("sound", "BBQ Ass", [[Interface\AddOns\ElvUI\media\sounds\bbqass.mp3]])
LSM:Register("sound", "Big Yankie Devil", [[Interface\AddOns\ElvUI\media\sounds\yankiebangbang.mp3]])
LSM:Register("sound", "Dumb Shit", [[Interface\AddOns\ElvUI\media\sounds\dumbshit.mp3]])
LSM:Register("sound", "Mama Weekends", [[Interface\AddOns\ElvUI\media\sounds\mamaweekends.mp3]])
LSM:Register("sound", "Runaway Fast", [[Interface\AddOns\ElvUI\media\sounds\runfast.mp3]])
LSM:Register("sound", "Stop Running", [[Interface\AddOns\ElvUI\media\sounds\stoprunningslimball.mp3]])
LSM:Register("sound","Warning", [[Interface\AddOns\ElvUI\media\sounds\warning.mp3]])
LSM:Register("sound","Whisper Alert", [[Interface\AddOns\ElvUI\media\sounds\whisper.mp3]])
LSM:Register("sound", "Kick Cast", [[Interface\AddOns\ElvUI\media\sounds\kickcast.mp3]])
LSM:Register("statusbar","ElvUI Gloss", [[Interface\AddOns\ElvUI\media\textures\normTex.tga]])
LSM:Register("statusbar","ElvUI Norm", [[Interface\AddOns\ElvUI\media\textures\normTex2.tga]])
LSM:Register("statusbar","Minimalist", [[Interface\AddOns\ElvUI\media\textures\Minimalist.tga]])
LSM:Register("statusbar","Eui_0", [[Interface\AddOns\ElvUI\media\textures\statusbar\0.tga]])
LSM:Register("statusbar","Eui_1", [[Interface\AddOns\ElvUI\media\textures\statusbar\1.tga]])
LSM:Register("statusbar","Eui_2", [[Interface\AddOns\ElvUI\media\textures\statusbar\2.tga]])
LSM:Register("statusbar","Eui_3", [[Interface\AddOns\ElvUI\media\textures\statusbar\3.tga]])
LSM:Register("statusbar","Eui_4", [[Interface\AddOns\ElvUI\media\textures\statusbar\4.tga]])
LSM:Register("statusbar","Eui_5", [[Interface\AddOns\ElvUI\media\textures\statusbar\5.tga]])
LSM:Register("statusbar","Eui_6", [[Interface\AddOns\ElvUI\media\textures\statusbar\6.tga]])
LSM:Register("statusbar","Eui_7", [[Interface\AddOns\ElvUI\media\textures\statusbar\7.tga]])
LSM:Register("statusbar","Eui_8", [[Interface\AddOns\ElvUI\media\textures\statusbar\8.tga]])
LSM:Register("statusbar","Eui_9", [[Interface\AddOns\ElvUI\media\textures\statusbar\9.tga]])
LSM:Register("statusbar","Eui_10", [[Interface\AddOns\ElvUI\media\textures\statusbar\10.tga]])
LSM:Register("statusbar","Eui_11", [[Interface\AddOns\ElvUI\media\textures\statusbar\11.tga]])
LSM:Register("statusbar","Line", [[Interface\AddOns\ElvUI\media\textures\statusbar\line.tga]])

LSM:Register("sao", "MASTER_MARKSMAN", [[TEXTURES\SPELLACTIVATIONOVERLAYS\MASTER_MARKSMAN.BLP]])
LSM:Register("sao", "FOCUS_FIRE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\FOCUS_FIRE.BLP]])
LSM:Register("sao", "LOCK_AND_LOAD", [[TEXTURES\SPELLACTIVATIONOVERLAYS\LOCK_AND_LOAD.BLP]])
LSM:Register("sao", "BLOOD_SURGE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\BLOOD_SURGE.BLP]])
LSM:Register("sao", "SWORD_AND_BOARD", [[TEXTURES\SPELLACTIVATIONOVERLAYS\SWORD_AND_BOARD.BLP]])
LSM:Register("sao", "SUDDEN_DEATH", [[TEXTURES\SPELLACTIVATIONOVERLAYS\SUDDEN_DEATH.BLP]])
LSM:Register("sao", "MAELSTROM_WEAPON", [[TEXTURES\SPELLACTIVATIONOVERLAYS\MAELSTROM_WEAPON.BLP]])
LSM:Register("sao", "FULMINATION", [[TEXTURES\SPELLACTIVATIONOVERLAYS\FULMINATION.BLP]])
LSM:Register("sao", "IMPACT", [[TEXTURES\SPELLACTIVATIONOVERLAYS\IMPACT.BLP]])
LSM:Register("sao", "FROZEN_FINGERS", [[TEXTURES\SPELLACTIVATIONOVERLAYS\FROZEN_FINGERS.BLP]])
LSM:Register("sao", "ARCANE_MISSILES", [[TEXTURES\SPELLACTIVATIONOVERLAYS\ARCANE_MISSILES.BLP]])
LSM:Register("sao", "HOT_STREAK", [[TEXTURES\SPELLACTIVATIONOVERLAYS\HOT_STREAK.BLP]])
LSM:Register("sao", "BRAIN_FREEZE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\BRAIN_FREEZE.BLP]])
LSM:Register("sao", "SURGE_OF_LIGHT", [[TEXTURES\SPELLACTIVATIONOVERLAYS\SURGE_OF_LIGHT.BLP]])
LSM:Register("sao", "MOLTEN_CORE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\MOLTEN_CORE.BLP]])
LSM:Register("sao", "BACKLASH", [[TEXTURES\SPELLACTIVATIONOVERLAYS\BACKLASH.BLP]])
LSM:Register("sao", "IMP_EMPOWERMENT", [[TEXTURES\SPELLACTIVATIONOVERLAYS\IMP_EMPOWERMENT.BLP]])
LSM:Register("sao", "NIGHTFALL", [[TEXTURES\SPELLACTIVATIONOVERLAYS\NIGHTFALL.BLP]])
LSM:Register("sao", "NATURES_GRACE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\NATURES_GRACE.BLP]])
LSM:Register("sao", "GENERICTOP_01", [[TEXTURES\SPELLACTIVATIONOVERLAYS\GENERICTOP_01.BLP]])
LSM:Register("sao", "ECLIPSE_SUN", [[TEXTURES\SPELLACTIVATIONOVERLAYS\ECLIPSE_SUN.BLP]])
LSM:Register("sao", "FURY_OF_STORMRAGE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\FURY_OF_STORMRAGE.BLP]])
LSM:Register("sao", "ECLIPSE_MOON", [[TEXTURES\SPELLACTIVATIONOVERLAYS\ECLIPSE_MOON.BLP]])
LSM:Register("sao", "SHOOTING_STARS", [[TEXTURES\SPELLACTIVATIONOVERLAYS\SHOOTING_STARS.BLP]])
LSM:Register("sao", "DARK_TRANSFORMATION", [[TEXTURES\SPELLACTIVATIONOVERLAYS\DARK_TRANSFORMATION.BLP]])
LSM:Register("sao", "SUDDEN_DOOM", [[TEXTURES\SPELLACTIVATIONOVERLAYS\SUDDEN_DOOM.BLP]])
LSM:Register("sao", "RIME", [[TEXTURES\SPELLACTIVATIONOVERLAYS\RIME.BLP]])
LSM:Register("sao", "KILLING_MACHINE", [[TEXTURES\SPELLACTIVATIONOVERLAYS\KILLING_MACHINE.BLP]])
LSM:Register("sao", "GRAND_CRUSADER", [[TEXTURES\SPELLACTIVATIONOVERLAYS\GRAND_CRUSADER.BLP]])
LSM:Register("sao", "ART_OF_WAR", [[TEXTURES\SPELLACTIVATIONOVERLAYS\ART_OF_WAR.BLP]])
LSM:Register("sao", "DAYBREAK", [[TEXTURES\SPELLACTIVATIONOVERLAYS\DAYBREAK.BLP]])
LSM:Register("sao", "HAND_OF_LIGHT", [[TEXTURES\SPELLACTIVATIONOVERLAYS\HAND_OF_LIGHT.BLP]])